### ISSUE TITLE
relation "report" does not exist

### ISSUE THREAD

**Issue by Fred-Leclercq** [baudev/gdpr-checker-backend#1]
After some tries,  the "migration_table" is created in the PostgreSQL DB
Unfortunately when performing a first test, I got this error:

[Nest] 80939   - 06/11/2021, 11:14:46 AM   [NestApplication] Nest application successfully started +2ms
[Nest] 80939   - 06/11/2021, 11:15:32 AM   [ExceptionsHandler] relation "report" does not exist +45964ms
**QueryFailedError: relation "report" does not exist**
    at new QueryFailedError (/home/fred/Downloads/gdpr-checker-backend/node_modules/typeorm/error/QueryFailedError.js:11:28)
    at PostgresQueryRunner.<anonymous> (/home/fred/Downloads/gdpr-checker-backend/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:247:31)
    at step (/home/fred/Downloads/gdpr-checker-backend/node_modules/typeorm/node_modules/tslib/tslib.js:141:27)
    at Object.throw (/home/fred/Downloads/gdpr-checker-backend/node_modules/typeorm/node_modules/tslib/tslib.js:122:57)
    at rejected (/home/fred/Downloads/gdpr-checker-backend/node_modules/typeorm/node_modules/tslib/tslib.js:113:69)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

Any ideas before I dive into the code? Thx!

**Comment by baudev** [comment]
There seems to be a problem (the demo version doesn't work anymore either).
I'll try to look at it when I have time, but if you find the problem don't hesitate to make a PR

**Comment by baudev** [comment]
I just redeployed the server from an empty database and no problem...
Were you able to find out where yours came from?

By the way, before installing this project on your machine, you can try the project demo: https://baudev.github.io/gdpr-checker-frontend/

**Comment by Fred-Leclercq** [comment]
Migrations were not executed by default ...

**Comment by baudev** [comment]
Ok so I close the issue.

Feel free to contribute to the repository and to give it a star to give it more visibility ⭐!
